rewrite `mpv` and update `bash` config

diff --git a/shell/.config/bash/40-appearance b/shell/.config/bash/40-appearance
--- a/shell/.config/bash/40-appearance
+++ b/shell/.config/bash/40-appearance
@@ -1,86 +1,64 @@
 prompt() {
-    local exit_status=$?
-
-    # use different colors depending on exit status
-    local reset accent1 accent2
+    # use different colors depending on last exit status
+    local reset accent_1 accent_2 exit_status=$?
 
     reset='\[\e[m\]'
 
-    ((exit_status)) && {
-        accent1='\[\e[32m\]'
-        accent2='\[\e[91m\]'
+    ((exit_status != 0)) && {
+        accent_1='\[\e[32m\]'
+        accent_2='\[\e[91m\]'
     } || {
-        accent1='\[\e[91m\]'
-        accent2='\[\e[32m\]'
+        accent_1='\[\e[91m\]'
+        accent_2='\[\e[32m\]'
     }
 
-    # different $HOME symbol when using ssh
+    # use different symbol for '$HOME' when using ssh
     local short_home
 
     [[ $SSH_TTY || $SSH_CLIENT ]] \
         && short_home='><>'       \
         || short_home='~'
 
-    # shorten long $PWDs
-    local short_pwd=$PWD
+    # shorten long '$PWD'
+    local -a parts short_pwd=$PWD
 
+    short_pwd=${short_pwd//$/\\$}   # $ => \$
     short_pwd=${short_pwd//\\/\\\\} # \ => \\
     short_pwd=${short_pwd//\`/\\\`} # ` => \`
-    short_pwd=${short_pwd//$/\\$}   # $ => \$
     short_pwd=${short_pwd/#$HOME/$short_home}
 
-    [[
-        $short_pwd =~ (.*/){3}.* &&
-        $short_pwd =~ ($short_home)?(/[^/]*/).*(/.*)
-    ]] && {
-        # save ourselves some typing
-        declare -n match=BASH_REMATCH
+    IFS='/' read -r -a parts <<< $short_pwd
 
-        short_pwd=${match[1]}${match[2]}...${match[3]}
-    }
+    ((${#parts[@]} > 3)) &&
+        short_pwd=${parts[0]}/${parts[1]}/.../${parts[@]: -1}
 
-    # set terminal title to the same thing
+    # set terminal title to '$short_pwd'
     local term_title
 
-    term_title="\[\e]0;$short_pwd\]\[\a\]"
+    term_title='\[\e]0;'$short_pwd'\]\[\a\]'
 
-    # ensure that the prompt is always printed on a newline
-    local position column
+    # set git status indicator
+    local -a git_output git_status current_dir=$PWD
 
-    IFS='[;' read -rsp $'\e[6n' -dR _ _ column
-
-    ((column > 1))           \
-        && position='\[\n\]' \
-        || position=
-
-    # git status indicator
-    local -a git_output git_status new_path old_path=$PWD
-
-    for ((;;)) {
-        [[ -d $old_path/.git ]] && {
+    while [[ $current_dir ]]; do
+        [[ -d $current_dir/.git ]] && {
             mapfile -t git_output <<< $(git status --branch --porcelain)
 
-            git_status=' ='
+            [[ $git_output =~ '[ahead '[0-9]+']'$ ]] \
+                && git_status=' +'                   \
+                || git_status=' ='
 
-            [[ $git_output =~ '[ahead '[0-9]+\]$ ]] &&
-                git_status=' +'
-
-            [[ ${#git_output[@]} -gt 1 ]] &&
+            ((${#git_output[@]} > 1)) &&
                 git_status=' !'
 
             break
         }
 
-        new_path=${old_path%/*}
-
-        test "$new_path" = "$old_path" &&
-            break
-
-        old_path=$new_path
-    }
+        current_dir=${current_dir%/*}
+    done
 
     # put the prompt together
-    PS1="$position$term_title$accent1$short_pwd$accent2$git_status$reset "
+    PS1="$term_title$accent_1$short_pwd$accent_2$git_status$reset "
 }
 
 PROMPT_COMMAND=prompt
@@ -110,4 +88,4 @@ st=44;30:\
 su=41;97:\
 tw=42;30:"
 
-# vim: ft=sh
+# vim: ft=bash
