update resize script
- better scripting practices
- add usage function

diff --git a/wm/.local/bin/resize b/wm/.local/bin/resize
--- a/wm/.local/bin/resize
+++ b/wm/.local/bin/resize
@@ -1,30 +1,46 @@
 #!/bin/sh
 #
-# resize - resize focused window in a given direction
+# resize - resize the focused window
 
-PERCENT=10
+die() {
+    printf '%s\n' \
+        "${1:-usage : ${0##*/} <east|west|north|south>}" >&2
+
+    exit 1
+}
+
+readonly PERCENT=10
+
+percent=$PERCENT
 
 # set a smaller percentage when floating
 bspc query -N -n focused.floating > /dev/null &&
-    PERCENT=$((PERCENT / 2))
+    : $((percent /= 2))
 
-case $1 in
-    east)  dim=w; dir=right; falldir=left;   sign=+;;
-    west)  dim=w; dir=right; falldir=left;   sign=-;;
-    north) dim=h; dir=top;   falldir=bottom; sign=-;;
-    south) dim=h; dir=top;   falldir=bottom; sign=+
+case $* in
+    east)  dim=w; dir=right; fb_dir=left  ; sign=+;;
+    west)  dim=w; dir=right; fb_dir=left  ; sign=-;;
+    north) dim=h; dir=top  ; fb_dir=bottom; sign=-;;
+    south) dim=h; dir=top  ; fb_dir=bottom; sign=+;;
+    *)
+        die
 esac
 
-# get a percentage of the monitor resolution
-var=$((`wattr "$dim" "$(lsw -r)"` * PERCENT / 100))
+# get a percentage of the resolution
+: $((var = $(wattr "$dim" "$(lsw -r)") * PERCENT / 100))
 
 case $dim in
     w) x=$sign$var; y=0;;
-    h) y=$sign$var; x=0
+    h) y=$sign$var; x=0;;
 esac
 
-# try to resize in one direction
-# fall back to the other if it fails
-bspc node -z "$dir" "$x" "$y" || bspc node -z "$falldir" "$x" "$y"
+# attempt to resize in one direction,
+# fallback to the other if it fails
+{
+    bspc node -z    "$dir" "$x" "$y" ||
+    bspc node -z "$fb_dir" "$x" "$y"
+} || exit 1
 
 cursor
+
+: # fix exit status
