update volume script
- better scripting practices
- add usage function & argument checking

diff --git a/wm/.local/bin/volume b/wm/.local/bin/volume
--- a/wm/.local/bin/volume
+++ b/wm/.local/bin/volume
@@ -1,16 +1,35 @@
 #!/bin/sh
 #
-# volume - control volume
+# volume - volume control
 
-var=$(amixer set Master "$1")
+die() {
+    printf '%s\n' "${1:-usage : ${0##*/} <offset|toggle>}" >&2
 
-test "$1" = toggle && exit
+    exit 1
+}
+
+# basic argument parsing
+case $* in
+    [0-9]%[+-])           ;;
+    [0-9][0-9]%[+-])      ;;
+    [0-9][0-9][0-9]%[+-]) ;;
+    toggle)               ;;
+    *)
+        die
+esac
+
+amixer_output=$(amixer set Master "$*")
+
+[ "$*" = toggle ] && exit
 
 # send a notification when fullscreen
 bspc query -N -n focused.fullscreen > /dev/null && {
     # format volume
-    var=${var%%]*}
-    var=${var#*[}
+    volume=$amixer_output
+    volume=${volume%%]*}
+    volume=${volume#*[}
 
-    dunstify -r 501 "Volume : $var"
+    dunstify -r 501 "Volume : $volume"
 }
+
+: # fix exit status
