apparently redirections are parts of code blocks

diff --git a/shell/.config/shell/70-command-not-found b/shell/.config/shell/70-command-not-found
--- a/shell/.config/shell/70-command-not-found
+++ b/shell/.config/shell/70-command-not-found
@@ -1,10 +1,8 @@
 type correct &> /dev/null &&
     command_not_found_handle() {
-        {
-            echo "${SHELL##*/} : command '$1' not found, did you mean :"
-            correct "$1"
-        } >&2
-    }
+        echo "${SHELL##*/} : command '$1' not found, did you mean :"
+        correct "$1"
+    } >&2
 
 :
 
