print to stderr

diff --git a/wm/bin/panel b/wm/bin/panel
--- a/wm/bin/panel
+++ b/wm/bin/panel
@@ -5,7 +5,7 @@
 name=panel
 
 if xdo id -a "$name" > /dev/null; then
-    echo 'error : panel already running'
+    echo 'error : panel already running' >&2
     exit 1
 fi
 
